id: A0CA80883
title: 'The Swift Infusion of Blessings: A Lineage Prayer for the Single Mind Kīla
  Heart-Practice, Part of the ''Neck Pouch Dagger’ (Purba Gulkhukma) Cycle'
type: translation
pechas:
- IFF63634C
- I127A24C4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:49:40.999276
  last_modified_at: 2023-01-04 12:49:40.999298
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  IFF63634C/4EEC: D7BC
  I127A24C4/4C45: D7BC
